#pragma once
#ifndef SETTINGS_H_
#define SETTINGS_H_

// CSV STUFF _____________________________________________________________________________

#define MAX_CSV_WIDTH 10
#define MAX_CSV_WIDTH_ITER_TYPE u8
#define MAX_CSV_LENGTH 500
#define MAX_CSV_LENGTH_ITER_TYPE u16
#define MAX_CSV_CELLS MAX_CSV_LENGTH * MAX_CSV_WIDTH // 5000
#define MAX_CSV_CELLS_ITER_TYPE u16
#define MAX_CSV_CELL_CONTENT_SIZE SMOL_TEXT_BUFF_SIZE // 1024
#define MAX_CSV_CELL_CONTENT_SIZE_ITER_TYPE SMOL_TEXT_BUFF_SIZE_ITER_TYPE

#define MAX_CSV_BUFFER_SIZE MAX_CSV_CELLS*MAX_CSV_CELL_CONTENT_SIZE * 1.1 // 5000 * 1024 * 1.1 = 5,632,000
#define MAX_CSV_BUFFER_SIZE_ITER_TYPE u32

#define CSV_FIRST_DEGREE_DELIMETER ','
#define CSV_SECOND_DEGREE_DELIMETER '\"'
#define CSV_NEWLINE_DELIMETER '\n'
#define CSV_NEWLINE_DELIMETER_STRING "\n"
#define CSV_END_OF_FILE '\0'

#define CSV_HEADER_ROW_POSITION 0
#define CSV_FIRST_DATA_ROW_POSITION 1 + CSV_HEADER_ROW_POSITION

// WORDLIST STUFF ________________________________________________________________________

#define MAX_WORDLIST_SIZE 500000
#define MAX_WORDLIST_SIZE_ITER_TYPE u32

#define DEFAULT_WORDLIST_SIZE 10000
#define DEFAULT_WORDLIST_PATH "./"

#define MAX_WORDLIST_FILE_BUFFER_SIZE MAX_WORDLIST_SIZE * MAX_CSV_CELL_CONTENT_SIZE
#define MAX_WORDLIST_FILE_BUFFER_SIZE_ITER_TYPE u32

#define WORDLIST_DELIMETER "\n"

#define WORDLIST_FILE_EXTENSION ".txt"

// ENCRYPTION STUFF ______________________________________________________________________

#define MAX_USER_SALT_LENGTH 255
#define MAX_USER_SALT_LENGTH_ITER_TYPE u8

#define SALT_STRING_SIZE TIME_T_CONVERTED_TO_STRING_POSSIBLE_BUFFER_SIZE + 1 + \
    MAX_USER_SALT_LENGTH + 1 // 20 + 1 + 255 + 1 = 277
#define SALT_STRING_SIZE_ITER_TYPE u16

#define OPEN_FILE_SIGNATURE_STRING_SIZE MAX_CSV_CELL_CONTENT_SIZE
#define OPEN_FILE_SIGNATURE_STRING_SIZE_ITER_TYPE MAX_CSV_CELL_CONTENT_SIZE_ITER_TYPE

#define DEFAULT_HASH_OCTET_LENGTH_PKCS5_PBKDF2_HMAC_SHA1 20 // Half of the string hash

#define FAULTY_RANDOM_COUNTER_LIMIT 50
#define FAULTY_RANDOM_COUNTER_LIMIT_ITER_TYPE u8

#define OPEN_FILE_SIGNATURE_DELIMETER "_"

#endif // SETTINGS_H_
